const msg = {
    socialError:"You can not login because you have registered by social login",
    notInTimeRange:"FromTime or ToTime not in the range of parking's parkIn or parkOut time",
    isParkingExists:"Parking is permanently closed no more service is available.Thank You",
    canNotDelete:"Cannot delete parking spot with active bookings",
    dataNotExist:"Parking not exist",
    HRM:"No Explore Point Exist Nearby",
    banner: "Banner id does not exist",
    productNotExist:"this product id not exits",
    invalidTransactionPin: "Invalid Transaction pin",
    validCryptoCurrency: "Only usdt,usdc,imt,eth,bitcoin,litecoin,xrp,airdrop are valid currencies",
    requiredTransactionPin:"Transaction Pin Required",
    requiredLocation:"GPS Service is not allowed location of user is required",
    notExist:"Booking id or User id Does'nt Exist",
    isWalletAmount:"You do not have sufficient amount in your wallet",
    success: "Ok",
    mandatoryPassword: "Password is mandatory",
    invalidOtp: "OTP is invalid",
    duplicateEmailOrMobile: "Already exists",
    invalidReferalCode: "invalid refferal code",
    invalidPassword: "Password is invalid",
    userExist: "User already exists",
    chatExist: "Chat already exists",
    userSignedupWihGoogle: "User is signed up with google.Try to login using google",
    userSignedupWithFacebook: "User is signed up with facebook.Try login using facebook",
    requiredOtp: "OTP is required",
    email: "Please provide email",
    userNotFound: "User not found",
    password_updated: "Password is successfully updated",
    userNotVerified: "User is unverified. Please check your mail to verify",
    loggedIn: "Successfully logIn",
    expireOtp: "OTP is expired",
    incorrectOTP: "OTP is incorrect",
    duplicateEmail: "Email already exists",
    duplicatePhone: "Contact number already exists",
    duplicateUnverifiedEmail: "This email Id is registered, but not verified",
    duplicateUnverifiedPhone: "This phone is registered, but not verified",
    emailOrMobileRequired: "You have to give mobile no or email",
    invalidCredentials: "Invalid credentials",
    badReq: "Bad request",
    serverError: 'Something went wrong, please try again...',
    passwordRequired: "Password required",
    invalidEmail: "Email address is invalid",
    resetPassword: 'Reset password link has been send.Please check your emails',
    resetPasssuccessful: "Password has been successfully updated",
    userDeleted: 'User is successfully deleted',
    NotExist: "Do not exist",
    alreadyViewed: "Already viewed",
    orderNotexist: "Order do not exist",
    NotCreated: "Do not created, try again",
    messageLimit: "Chat message limit reached for current plan",
    requestLimit: "Request limit reached for current plan",
    invalidSender: "Invalid sender",
    failedTransaction: "Transaction failed",
    CouponNotExist: "Coupon dose not exist",
    actionForbidden: "This action is forbidden. You don't have permission to do this",
    notAvailable: 'Not available',
    notValidCode: 'Code is not valid',
    unauthorisedRequest: 'Unauthorised request',
    passwordUpdated: 'Password updated successfully',
    invalidVerficationCode: 'Please enter a valid verification code',
    invalidForgotCode: 'Invalid forgot code',
    invalidCategoryId: 'Invalid category id',
    invalidSubcategoryId: 'Invalid subcategory id',
    invalidSubSubcategoryId: 'Invalid sub sub category id',
    invalidProductId: 'Invalid product id',
    removedFromWishlist: 'Item successfully removed from wishlist',
    removedFromSaveForLater: 'Item successfully removed from save for later',
    addedInWishlist: 'Item successfully added in wishlist',
    addedInVocab: 'Word successfully added.',
    addedInCYH: 'Item successfully added in CYH',
    addedInSaveForLater: 'Item successfully added in save for later',
    invalidId: 'Please enter valid id',
    invalidUserId: 'Please enter valid User id',
    invalidAddressId: 'Please enter valid Address id',
    productNotExist: 'This product not exist',
    invalidBrandId: 'Provided brand id is invalid',
    unexpectedError: 'Some unexpected error occured. Please try again later',
    unverifiedForgotPasswordReq: 'Invalid request. The forgot password code is not verified',
    invalidBlogId: 'Please enter valid blog id',
    seasonNotValid: 'This season is invalid',
    noSeasonAvailable: 'No season is available at this moment',
    OrderCanceledSuccessfully: 'Your Order has been canceled successsfully',
    tooLateToCancelOrder: 'Now you are late to cancel your order',
    invalidDetails: "Invalid Id",
    NotExistOrNotActive: "Not Exist Or Not Active",
    OrderListIsEmpty: "Order list is empty",
    speedListIsEmpty: "Speed date chat is empty",
    canNotDeliverAtThisPin: "Can not deliver at this PinCode",
    noProductAvailableForShipping: "No product available for shipping",
    productIsOutOfStock: "This product is out of stock",
    paymentFailed: "Payment failed",
    notSaved: "Not saved",
    otpVerified: "OTP has been verified",
    otpNotVerified: "OTP is invalid",
    couponCodeCanNotBeApplied: "Your payable ammount is less then given minimum ammount. So that coupon can not be applied",
    couponNotExist: "This coupon dose not exist",
    couponIsNotApplicable: "This coupon code is not applicable for you",
    hintTitleRequired: "Hint Title is required",
    hintContentRequired: "Hint Content is required",
    questionRequired: "Question Required.",
    questionIdRequired: "Question Id Required.",
    answerIdRequired: "Answer Id required",
    invalidHintId: "Hint Id Invalid",
    invalidBalance: 'Insufficient balance',
    blockedByuser: 'Blocked By User',
    norewardearn: "You Have no rewards Yet",
    blockByUser: "You Have been Blocked By Admin",
    CardnotExist: 'Card not exist',
    Cardnotfound: 'Card not found',
    UsernotExist: 'User Not Exist',
    GiftNotFound: 'Gift Not Exist',
    hotelnotExist: 'HotelNotExist',
    Nofeedback: 'NoFeedbacks',
    NoReward: "NoReward",
    NoHints: "NoHints",
    FAQNotFound: "FAQNotFound",
    NoRedeem: 'NoRedee',
    notificationNotFound: 'No Notification Exists',
    alreadyMining: 'Mining is already initiated',
    notAllowed: "You're not allowed to do that",
    notVerified:"First you have to verify",
    notRegistered:"This email or phone is not registered",
    insufficientWalletAmount:"We can't process your request because you don't have sufficient balance in your wallet for this. You can also pay with credit/debit card.",
    markedOrUnmarked:"Not successfull",
    marked:"Marked users",
    unmarked:"Not exist"
}

module.exports = { msg };